[outputs]
home = ["HTML", "RSS", "JSON"]

[params.astryx]
mainSections = ["posts"]
showToc = true
defaultMode = "system"

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]

[markup.highlight]
noClasses = false

[module.hugoVersion]
min = "0.146.0"
