import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { renderToStaticMarkup } from 'react-dom/server';
import { AppShell } from '@astryxdesign/core/AppShell';
import { TopNav, TopNavHeading, TopNavItem } from '@astryxdesign/core/TopNav';
import { Text, Heading } from '@astryxdesign/core/Text';
import { Section } from '@astryxdesign/core/Section';
import { Button } from '@astryxdesign/core/Button';
import { Badge } from '@astryxdesign/core/Badge';
import { Divider } from '@astryxdesign/core/Divider';
import { Link } from '@astryxdesign/core/Link';
import { HStack } from '@astryxdesign/core/Layout';
import { Icon } from '@astryxdesign/core/Icon';
import { AspectRatio } from '@astryxdesign/core/AspectRatio';
import { Breadcrumbs, BreadcrumbItem } from '@astryxdesign/core/Breadcrumbs';
import { TextInput } from '@astryxdesign/core/TextInput';
import { Theme } from '@astryxdesign/core/theme';
import { astryxTheme } from '../assets/css/generated/astryx.js';
import { BrandMark } from '../src/brand.jsx';
import { BlogCoverArt } from '../src/cover-art.jsx';
import { siteIcons as icons } from '../src/icons.mjs';

const output = resolve(process.cwd(), 'layouts/_partials/ui');
await mkdir(output, {recursive: true});
const slots = {
  SLOT_TEXT: '{{ .text }}', SLOT_LANG: '{{ .lang | default "" }}',
  SLOT_TITLE: '{{ .title }}', SLOT_HOME: '{{ .homeURL }}', SLOT_HREF: '{{ .href }}',
  SLOT_LABEL: '{{ .label }}', SLOT_ITEMS: '{{ .itemsHTML | safeHTML }}',
  SLOT_ACTIONS: '{{ .actionsHTML | safeHTML }}', SLOT_CONTENT: '{{ .content | safeHTML }}',
};
function html(element, extra = {}) {
  let result = renderToStaticMarkup(element);
  // Longer names such as SLOT_TEXT_LANG must be resolved before SLOT_TEXT.
  const replacements = Object.entries({...slots, ...extra}).sort(([a], [b]) => b.length - a.length);
  for (const [key, value] of replacements) result = result.replaceAll(key, value);
  return result;
}
async function save(name, value) {
  await writeFile(resolve(output, `${name}.html`), '{{/* Generated by scripts/render-ui.jsx from actual Astryx components. */}}\n' + value + '\n');
}

const shell = html(<Theme theme={astryxTheme} mode="system"><AppShell variant="surface" height="auto" mobileNav={false}
  topNav={<div id="astryx-header">SLOT_HEADER</div>}><div id="main-content">SLOT_MAIN</div></AppShell></Theme>, {
    SLOT_HEADER: '{{ partial "header.html" . }}',
    SLOT_MAIN: 'SLOT_MAIN',
  }).replace('Skip to content', '{{ i18n "skipToContent" }}').replace('href="#astryx-app-shell-main"', 'href="#astryx-app-shell-main" lang="{{ partial "ui-locale.html" . }}"');
// Hugo emits the theme scope on html; the static Theme wrapper must inherit
// the user's document color scheme when the client root changes appearance.
const themedShell = shell.replace('class="', 'style="color-scheme:inherit" class="');
const [shellOpen, shellClose] = themedShell.split('SLOT_MAIN');
await save('shell-open', shellOpen);
await save('shell-close', shellClose);
const topNav = logoURL => html(<TopNav label="SLOT_NAV_LABEL"
  heading={<TopNavHeading logo={<BrandMark src={logoURL}/>} heading="SLOT_TITLE" headingHref="SLOT_HOME"/>}
  centerContent={<div className="site-nav-desktop">SLOT_ITEMS</div>}
  endContent={<HStack gap={2} className="site-nav-actions">SLOT_ACTIONS</HStack>}/>, {
    SLOT_NAV_LABEL:'{{ .navLabel }}', SLOT_LOGO_URL:'{{ .logoURL }}',
  });
await save('top-nav', '{{ if .logoURL }}' + topNav('SLOT_LOGO_URL') + '{{ else }}' + topNav() + '{{ end }}');
const item = selected => html(<TopNavItem label="SLOT_LABEL" href="SLOT_HREF" isSelected={selected}/>);
await save('top-nav-item', '{{ if .selected }}' + item(true) + '{{ else }}' + item(false) + '{{ end }}');
await save('page-title', html(<Heading level={1} type="display-1" lang="SLOT_LANG">SLOT_TEXT</Heading>));
await save('description', html(<Text as="p" type="large" color="secondary" weight="normal" lang="SLOT_LANG">SLOT_TEXT</Text>));
await save('card-title', '{{ if .feature }}' + html(<Heading level={2} type="heading-1" lang="SLOT_LANG" className="post-title feature-title">SLOT_TEXT</Heading>)
  + '{{ else }}' + html(<Heading level={2} type="heading-3" lang="SLOT_LANG" className="post-title">SLOT_TEXT</Heading>) + '{{ end }}');
await save('text', html(<Text as="p" type="body" weight="normal" color="secondary" lang="SLOT_LANG">SLOT_TEXT</Text>));
await save('supporting', html(<Text type="supporting" color="secondary" lang="SLOT_LANG">SLOT_TEXT</Text>));
await save('divider', html(<Divider/>));
await save('badge', html(<Badge label="SLOT_TEXT" variant="neutral"/>));
await save('button', html(<Button label="SLOT_LABEL" href="SLOT_HREF" variant="secondary"/>));
await save('action-button', html(<Button label="SLOT_LABEL" type="button" variant="secondary" data-comments-load>
  <span data-comments-action-label>SLOT_LABEL</span>
</Button>));
await save('submit-button', html(<Button label="SLOT_LABEL" type="submit" variant="primary" className="search-submit"/>));
await save('search-input', html(<TextInput label="SLOT_LABEL" placeholder="SLOT_PLACEHOLDER" value="" onChange={()=>{}}
  htmlName="q" id="search-input" type="search" data-search-input="true" className="search-input" isLabelHidden width="100%"/>, {SLOT_PLACEHOLDER:'{{ .placeholder }}'}));
await save('link', html(<Link href="SLOT_HREF" color="secondary" type="supporting" isStandalone>SLOT_LABEL</Link>));
await save('index-link', html(<Link href="SLOT_HREF" label="SLOT_LABEL" color="inherit" display="block" className="index-link">SLOT_CONTENT</Link>));
await save('toc-icon', html(<Icon icon="chevronDown" size="sm" className="article-toc-icon"/>));
const articleNavLink = direction => html(<Link href="SLOT_HREF" rel={direction} color="inherit" display="block" className={`article-nav-link article-nav-${direction}`}>
  <span className="article-nav-body">
    <span className="article-nav-label" lang="SLOT_UI_LANG"><Icon icon={direction === 'prev' ? 'chevronLeft' : 'chevronRight'} size="sm"/><Text type="supporting" color="secondary">SLOT_LABEL</Text></span>
    <Text type="body" weight="medium" color="primary" className="article-nav-title" lang="SLOT_LANG">SLOT_TEXT</Text>
  </span>
</Link>, {SLOT_UI_LANG: '{{ .uiLang | default "" }}'});
await save('article-nav-link', '{{ if eq .direction "prev" }}' + articleNavLink('prev') + '{{ else }}' + articleNavLink('next') + '{{ end }}');
const pageLink = current => html(<Button label="SLOT_LABEL" href="SLOT_HREF" rel="SLOT_REL" size="sm" variant={current ? 'secondary' : 'ghost'} aria-current={current ? 'page' : undefined} className="pagination-link"/>, {SLOT_REL: '{{ .rel | default "" }}'});
await save('page-link', '{{ if .current }}' + pageLink(true) + '{{ else }}' + pageLink(false) + '{{ end }}');
const cardLink = feature => html(<Link href="SLOT_HREF" label="SLOT_LABEL" color="inherit" display="block" className="post-link">
  <div className="post-card-body">SLOT_CONTENT</div>
</Link>);
await save('card-link', '{{ if .feature }}' + cardLink(true) + '{{ else }}' + cardLink(false) + '{{ end }}');
await save('search-link', html(<Button label="SLOT_LABEL" href="SLOT_HREF" variant="ghost" isIconOnly icon={icons.search}/>));
await save('section', html(<Section maxWidth={800} padding={6} className="blog-section">SLOT_CONTENT</Section>));
await save('cover', html(<AspectRatio ratio={16/9} className="post-cover">SLOT_CONTENT</AspectRatio>));
await save('breadcrumbs', html(<Breadcrumbs label="SLOT_BREADCRUMBS"><BreadcrumbItem href="SLOT_HREF">SLOT_LABEL</BreadcrumbItem><BreadcrumbItem isCurrent><span lang="SLOT_TEXT_LANG">SLOT_TEXT</span></BreadcrumbItem></Breadcrumbs>, {
  SLOT_BREADCRUMBS: '{{ i18n "breadcrumbs" }}', SLOT_TEXT_LANG: '{{ .textLang | default "" }}',
}));
await mkdir(resolve(output, 'covers'), {recursive: true});
for (let i = 0; i < 6; i++) await save(`covers/${i}`, html(<BlogCoverArt seed={`astryx-journal-${i}`} feature/>));
await save('cover-art', '{{ $hash := hash.FNV32a .seed }}{{ $variant := mod $hash 6 }}{{ partial (printf "ui/covers/%d.html" $variant) . }}');
console.log('Rendered Astryx AppShell, TopNav, text, cards, breadcrumbs, badges and controls as Hugo partials.');
